spring:
  application:
    name: tdd1
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306
    username: dmitry
    password: dbfwkqndfls*51
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update # or create, create-drop, validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

